name: A- Download and Split Plex EPG

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'  # Runs daily at 00:30 UTC

jobs:
  split-plex-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create required folders
        run: |
          mkdir -p download_EPG/External
          mkdir -p download_EPG/individual/US_Plex

      - name: Download Plex US EPG
        run: curl -L -o download_EPG/External/Plex_US.xml https://raw.githubusercontent.com/matthuisman/i.mjh.nz/refs/heads/master/Plex/us.xml

      - name: Split Plex EPG into per-channel files
        run: |
          python3 - << 'EOF'
          import xml.etree.ElementTree as ET
          import os, re

          src = "download_EPG/External/Plex_US.xml"
          tree = ET.parse(src)
          root = tree.getroot()
          tv_attrs = " ".join(f'{k}="{v}"' for k,v in root.attrib.items())

          out_dir = "download_EPG/individual/US_Plex"
          for channel in root.findall("channel"):
              cid = channel.get("id")
              disp = channel.findtext("display-name") or cid
              safe_name = re.sub(r'[^\w\-.]', '_', disp.strip())
              fname = f"Plex_{safe_name}.xml"
              path = os.path.join(out_dir, fname)

              progs = [p for p in root.findall("programme") if p.get("channel") == cid]

              with open(path, "w", encoding="utf-8") as f:
                  f.write("<?xml version='1.0' encoding='UTF-8'?> <!DOCTYPE tv SYSTEM \"xmltv.dtd\">\n")
                  f.write(f"<tv {tv_attrs}>\n")
                  f.write(ET.tostring(channel, encoding="unicode"))
                  f.write("\n")
                  for p in progs:
                      f.write(ET.tostring(p, encoding="unicode"))
                      f.write("\n")
                  f.write("</tv>\n")
          EOF

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull --rebase --autostash
          git add download_EPG/External/Plex_US.xml download_EPG/individual/US_Plex/
          git commit -m "Download and split Plex EPG into per-channel files $(date +%Y-%m-%d)" || echo "No changes"
          git push
