name: A- Update Plex EPG

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'  # Runs daily at 00:30 UTC

jobs:
  clean-plex-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create external folder if missing
        run: mkdir -p download_EPG/External

      - name: Download Plex US EPG
        run: curl -L -o download_EPG/External/Plex_US.xml https://raw.githubusercontent.com/matthuisman/i.mjh.nz/refs/heads/master/Plex/us.xml

      - name: Remove excluded channels and programs
        run: |
          ids=$(grep -oP '(?<=<channel id=")[^"]+' EPG/excluded/List.txt || true)
          for id in $ids; do
            echo "Removing channel id: $id"
            sed -i "/<channel id=\"$id\"/,/<\/channel>/d" download_EPG/External/Plex_US.xml
            sed -i "/<programme channel=\"$id\"/,/<\/programme>/d" download_EPG/External/Plex_US.xml
          done

      - name: Update QWEST channel Metadata
        run: |
          FILE="download_EPG/External/Plex_US.xml"
          cp "$FILE" "${FILE}.qwest.bak"
          TARGET_ID="5e20b730f2f8d5003d739db7-60b0f65c0c8ffb002c821a75"
          awk -v id="$TARGET_ID" '
          BEGIN {
            RS="</programme>"; ORS=""
            icon = "<icon src=\"https://blogs.library.american.edu/mediaservices/wp-content/uploads/sites/6/2024/10/Qwest-TV-720x380.jpg\"/>"
          }
          {
            if ($0 ~ "programme channel=\"" id "\"") {
              gsub(/<icon[^>]*\/>/, "")
              gsub("<category>Movie</category>", "<category>Music</category>")
              sub(/(<title[^>]*>.*?<\/title>)/, "\\1\n" icon)
            }
            print $0 "</programme>\n"
          }' "${FILE}.qwest.bak" > "$FILE"

      - name: Update Trace Urban channel metadata
        run: |
          FILE="download_EPG/External/Plex_US.xml"
          cp "$FILE" "${FILE}.traceurban.bak"
          TARGET_ID="5e20b730f2f8d5003d739db7-6322658be67cf9cd9011fcda"
          awk -v id="$TARGET_ID" '
          BEGIN {
            RS="</programme>"; ORS=""
            icon = "<icon src=\"https://provider-static.plex.tv/epg/cms/production/7ffb84ed-f5a5-4e57-973d-e1281b70fb17/trace_urban_artwork_horizontal_-_Nathan_BECKER.jpg\"/>"
          }
          {
            if ($0 ~ "programme channel=\"" id "\"") {
              gsub(/<icon[^>]*\/>/, "")
              gsub("<category>Movie</category>", "<category>Music</category>")
              sub(/(<title[^>]*>.*?<\/title>)/, "\\1\n" icon)
            }
            print $0 "</programme>\n"
          }' "${FILE}.traceurban.bak" > "$FILE"

      - name: Fix XML Declaration formatting
        run: |
          for f in download_EPG/External/*.xml; do
            echo "Fixing declaration in $f"
            sed -i "1s|<?xml version=\"1.0\" encoding=\"UTF-8\"?>|<?xml version='1.0' encoding='UTF-8'?> |" "$f"
            sed -i "1s|?><!DOCTYPE|?> <!DOCTYPE|" "$f"
          done

      - name: Fix misplaced closing tags at end of file
        run: |
          for f in download_EPG/External/*.xml; do
            # Delete any </programme> lines that occur after the closing </tv> tag
            awk '
              /<\/tv>/ {tvClosed=1; print; next}
              tvClosed && /<\/programme>/ {next}
              {print}
            ' "$f" > "${f}.fixed"
            mv "${f}.fixed" "$f"
          done

      - name: Commit and push if modified
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull --rebase --autostash
          git add download_EPG/External/Plex_US.xml
          git commit -m "Cleaned Plex EPG $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push
