name: A- Update Plex EPG 

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'  # Runs daily at 00:30 UTC


jobs:
  clean-plex-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create external folder if missing
        run: mkdir -p download_EPG/External

      - name: Download Plex US EPG
        run: curl -L -o download_EPG/External/Plex_US.xml https://raw.githubusercontent.com/matthuisman/i.mjh.nz/refs/heads/master/Plex/us.xml

      - name: Remove excluded channels and programs
        run: |
          # Extract all channel ids from exclusion list
          ids=$(grep -oP '(?<=<channel id=")[^"]+' EPG/excluded/List.txt)
          for id in $ids; do
            echo "Removing channel id: $id"
            # Remove <channel> entries
            sed -i "/<channel id=\"$id\"/,/<\/channel>/d" download_EPG/External/Plex_US.xml
            # Remove <programme> entries for that channel
            sed -i "/<programme channel=\"$id\"/,/<\/programme>/d" download_EPG/External/Plex_US.xml
          done

      - name: Update QWEST channel metadata
        run: |
          FILE="download_EPG/External/Plex_US.xml"
          TARGET_ID="5e20b730f2f8d5003d739db7-60b0f65c0c8ffb002c821a75"
          NEW_ICON="https://blogs.library.american.edu/mediaservices/wp-content/uploads/sites/6/2024/10/Qwest-TV-720x380.jpg"

          cp "$FILE" "${FILE}.bak"

          awk -v id="$TARGET_ID" -v icon="$NEW_ICON" '
          BEGIN { RS="</programme>"; ORS="" }
          {
            if ($0 ~ "programme channel=\"" id "\"") {
              gsub("<category>Movie</category>", "<category>Music</category>")
              gsub(/<icon src="[^"]*"\/>/, "<icon src=\"" icon "\"/>")
            }
            print $0 "</programme>\n"
          }' "$FILE.bak" > "$FILE"


          
      - name: Fix XML Declaration formatting
        run: |
          for f in download_EPG/External/*.xml; do
            echo "Fixing declaration in $f"
            sed -i "1s/<?xml version=\"1.0\" encoding=\"UTF-8\"?>/<?xml version='1.0' encoding='UTF-8'?>/" "$f"
            sed -i "1s/?><!DOCTYPE/?> <!DOCTYPE/" "$f"
          done

      - name: Commit and push if modified
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull --rebase --autostash
          git add download_EPG/External/Plex_US.xml
          git commit -m "Cleaned Plex EPG $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push
