name: B - Update TRACE Urban Genre

on:
  workflow_run:
    workflows: ["A- Download and Split Plex EPG"]
    types:
      - completed

jobs:
  replace-genre:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace Movie genre with Music in Plex_TRACE_Urban.xml
        run: |
          FILE="download_EPG/individual/US_Plex/Plex_TRACE_Urban.xml"
          if [ -f "$FILE" ]; then
            echo "Processing $FILE"
            sed -i 's|<category>Movie</category>|<category>Music</category>|g' "$FILE"
          else
            echo "File not found: $FILE"
            exit 1
          fi

      - name: Commit and push if modified
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull --rebase --autostash
          git add download_EPG/individual/US_Plex/Plex_TRACE_Urban.xml
          git commit -m "Replaced Movie genre with Music for TRACE Urban" || echo "No changes to commit"
          git push
